@startuml
skinparam actorStyle awesome
package Users {
    actor "Client Side User" as ClientSideUser
    actor "Mobile User 1" as MobileUser1
    actor "Mobile User 2" as MobileUser2
    actor "Mobile User 3" as MobileUser3
}



rectangle Application {
    package "Client Side" {
    usecase MainMenu as "Main Menu
    --
    Client Side User is presented with game modes to choose from."
    usecase LobbyCS as "Lobby
    --
    Users are presented with a QR code
    or character code (ex: 3ER7U) to input
    into their mobile phones to access the lobby.

    Server asks users to Input Name"
    usecase Question as "Question
    --
    Users are presented with a question."
    usecase Answer as "Answer
    --
    Once all answers are submitted users
    will be displayed all submitted answers
    and the correct one with an explanation."
    usecase End as "Game Ends
    --
    Game ends once question bank has
    been gone through."
    }

    package "Server" {
    usecase Server as "Server
    --
    Is the middlleman with very little responsibility,
    except for maybe validating inputs and
    preventing malicious behavior"
    usecase ServerL as "Server Lobby
    --
    Validates userinput from Mobile Client
    such as Name from users."
    usecase ServerQ as "Server Question
    --
    Validates user input from Mobile Client
    such as Answers from users"

    }


    package "Mobile" {
    usecase UserInput as "User Input
    --
    User Input QR code or
    character to code into client
    to gain access to the lobby."
    usecase LobbyM as "Lobby
    --
    Users wait for ClientSideUser to
    start the game once they decide all
    the players are in the lobby."
    usecase SelectAnswers as "Answer Selection
    --
    Users are presented with answers to
    select or fill in based on the question."
    }
}
ClientSideUser -->  MainMenu
MainMenu --> LobbyCS
LobbyCS --> Question
Question --> Answer
Question  -> ServerQ
Answer --> Question
Answer --> End


MobileUser1 -> UserInput
MobileUser2 -> UserInput
MobileUser3 -> UserInput
ClientSideUser -> UserInput
UserInput --> LobbyM
LobbyM --> SelectAnswers
SelectAnswers  -> ServerQ


Server . ServerL
ServerQ . Server


LobbyCS --> ServerL
LobbyM  --> ServerL

@enduml